CREATE TABLE IF NOT EXISTS orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  session_id CHAR(32) NOT NULL UNIQUE,
  citizen_id VARCHAR(20) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  vin VARCHAR(50) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  brand VARCHAR(50) NOT NULL,
  desired_plates JSON NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
